version: '3'
services:
  worker:
    container_name: hearts
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8080:80"
      - "443:443"
    volumes:
      - .:/var/www/html
    environment:
      XDEBUG_CONFIG: "remote_host=host.docker.internal remote_port=9000"
      PHP_IDE_CONFIG: "serverName=localhost"
